INSERT INTO users (username, password, user_admin, gdpr) VALUES ('testuser1', 'testitesti', 'user', 'gdpr');
INSERT INTO users (username, password, user_admin, gdpr) VALUES ('testuser2', 'testitesti', 'user', 'gdpr');
INSERT INTO users (username, password, user_admin, gdpr) VALUES ('testadmin1', 'testitesti', 'admin', 'gdpr');
INSERT INTO users (username, password, user_admin, gdpr) VALUES ('testadmin2', 'testitesti', 'admin', 'gdpr');

INSERT INTO quizzes (quiz_label, created_by, published, category) VALUES ('Testquiz1', 'testadmin1', 'true', 'Movies and Games');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Testquestion1');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Testquestion2');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Testquestion3');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Testquestion4');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Testquestion5');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('1', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('1', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('1', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('2', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('2', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('2', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('3', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('3', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('3', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('4', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('4', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('4', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('5', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('5', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('5', 'Testoption3');

INSERT INTO quizzes (quiz_label, created_by, published, category) VALUES ('Testquiz2', 'testadmin2', 'true', 'Popular Music');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Testquestion1');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Testquestion2');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Testquestion3');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Testquestion4');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Testquestion5');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('6', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('6', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('6', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('7', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('7', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('7', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('8', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('8', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('8', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('9', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('9', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('9', 'Testoption3');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('10', 'Testoption1', 'True');
INSERT INTO options (question_id, option_label) VALUES ('10', 'Testoption2');
INSERT INTO options (question_id, option_label) VALUES ('10', 'Testoption3');

