INSERT INTO users (username, password, user_admin, gdpr) VALUES ('King of Rock', 'testitesti', 'admin', 'gdpr');
INSERT INTO users (username, password, user_admin, gdpr) VALUES ('Mozart', 'testitesti', 'admin', 'gdpr');

INSERT INTO quizzes (quiz_label, created_by, published, category) VALUES ('Just another popquiz', 'Mozart', 'true', 'Popular Music');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Which artist released the hit song "Blinding Lights" in 2019?');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Which song by Luis Fonsi and Daddy Yankee, featuring Justin Bieber, became a global hit in 2017?');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Which female artist had a massive hit with the song "Hello" in 2015?');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Which band released the album "A Rush of Blood to the Head" in 2002?');
INSERT INTO questions (quiz_id, question_label) VALUES ('1', 'Which song by Billie Eilish won the Grammy Award for Record of the Year in 2020?');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('1', 'The Weeknd', 'True');
INSERT INTO options (question_id, option_label) VALUES ('1', 'Drake');
INSERT INTO options (question_id, option_label) VALUES ('1', 'Post Malone');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('2', 'Despacito', 'True');
INSERT INTO options (question_id, option_label) VALUES ('2', 'Shape of You');
INSERT INTO options (question_id, option_label) VALUES ('2', 'Sorry');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('3', 'Adele', 'True');
INSERT INTO options (question_id, option_label) VALUES ('3', 'Beyoncé');
INSERT INTO options (question_id, option_label) VALUES ('3', 'Taylor Swift');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('4', 'Coldplay', 'True');
INSERT INTO options (question_id, option_label) VALUES ('4', 'Radiohead');
INSERT INTO options (question_id, option_label) VALUES ('4', 'U2');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('5', 'Bad Guy', 'True');
INSERT INTO options (question_id, option_label) VALUES ('5', 'Ocean Eyes');
INSERT INTO options (question_id, option_label) VALUES ('5', 'Everything I Wanted');

INSERT INTO quizzes (quiz_label, created_by, published, category) VALUES ('Easy Listening', 'King of Rock', 'true', 'Classical Music');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Which composer wrote the famous piece "Clair de Lune"?');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Which composer is known for the "Four Seasons," a set of four violin concertos?');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Which symphony by Ludwig van Beethoven is known as the "Choral Symphony"?');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Which composer is often referred to as the "Father of the Symphony"?');
INSERT INTO questions (quiz_id, question_label) VALUES ('2', 'Who composed the opera "The Magic Flute"?');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('6', 'Claude Debussy', 'True');
INSERT INTO options (question_id, option_label) VALUES ('6', 'Frédéric Chopin');
INSERT INTO options (question_id, option_label) VALUES ('6', 'Ludwig van Beethoven');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('7', 'Antonio Vivaldi', 'True');
INSERT INTO options (question_id, option_label) VALUES ('7', 'Wolfgang Amadeus Mozart');
INSERT INTO options (question_id, option_label) VALUES ('7', 'Johann Sebastian Bach');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('8', 'Symphony No. 9', 'True');
INSERT INTO options (question_id, option_label) VALUES ('8', 'Symphony No. 5');
INSERT INTO options (question_id, option_label) VALUES ('8', 'Symphony No. 7');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('9', 'Joseph Haydn', 'True');
INSERT INTO options (question_id, option_label) VALUES ('9', 'Pyotr Ilyich Tchaikovsky');
INSERT INTO options (question_id, option_label) VALUES ('9', 'ohannes Brahm');
INSERT INTO options (question_id, option_label, correct_option) VALUES ('10', 'Wolfgang Amadeus Mozart', 'True');
INSERT INTO options (question_id, option_label) VALUES ('10', 'Richard Wagner');
INSERT INTO options (question_id, option_label) VALUES ('10', 'Giuseppe Verdi');

